name: 📦 Create and publish Production Docker image

on:
    schedule:
        - cron: "0 10 * * *"
    workflow_dispatch:
    push:
        branches:
            - main
        tags:
            - "v*.*.*"
    pull_request:
        branches:
            - "main"

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  submodules: recursive

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
              with:
                  # list of Docker images to use as base name for tags
                  images: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  # generate Docker tags based on the following events/attributes
                  tags: |
                      type=schedule
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=sha

            - name: Log in to the Container registry
              uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
