name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  COMPOSER_CACHE_DIR: /tmp/_composer_cache

jobs:
  unit-tests:
    name: Tests for php${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
        coverage: xdebug
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Cache composer cache directory
      uses: actions/cache@v4
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: composer-cache
    - name: Unit tests
      run: |
        composer install
        composer test

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
        coverage: xdebug
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Cache composer cache directory
      uses: actions/cache@v4
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: composer-cache
    - name: Unit tests
      run: |
        composer install
        result=0
        composer run cs || result=1
        composer run phpstan || result=1
        composer run psalm || result=1
        exit $result

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, linting]
    if: github.ref == 'refs/heads/main'
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy and wait for completion
        if: github.ref == 'refs/heads/main'
        uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
        with:
          host: 'gitlab.tugraz.at'
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: '21238'
          ref: 'main'
          variables: '{"UPSTREAM_PROJECT_PATH":"dbp/relay/dbp-relay-server-template","UPSTREAM_COMMIT_BRANCH":"${{ github.ref_name }}","UPSTREAM_COMMIT_SHA":"${{ github.ref_name }}"}'
